FORMAT: 1A

HOST: http://leedsempties.nickjackson.me/

# Leeds Empty Homes
The Leeds Empty Homes API retrieves information on properties in Leeds.

# Group Wards
Retrieve information on wards, or organised by ward.

## Long Term Voids [/ajax/ward/long_term_voids{?name,callback}]

+ Parameters
    + name (required, string, `Temple Newsam`) ... Name of the ward to retrieve long term void information for.
    + callback (optional, string, `callback`) ... Name of the callback function, if required.

### GET
+ Response 200 (application/json)

        {
            "success": true,
            "ward": {
                "id": 31,
                "created_at": "2015-02-11 15:08:48",
                "updated_at": "2015-02-11 15:08:48",
                "name": "Temple Newsam",
                "long_term_voids": [
                    {
                        "id": 2911,
                        "created_at": "2015-02-11 15:37:17",
                        "updated_at": "2015-02-11 15:37:17",
                        "ward_id": 31,
                        "date": "2006-12-01 00:00:00",
                        "count": 127
                    },
                    {
                        "id": 2912,
                        "created_at": "2015-02-11 15:37:17",
                        "updated_at": "2015-02-11 15:37:17",
                        "ward_id": 31,
                        "date": "2007-01-01 00:00:00",
                        "count": 124
                    },
                    {
                        "id": 2913,
                        "created_at": "2015-02-11 15:37:17",
                        "updated_at": "2015-02-11 15:37:17",
                        "ward_id": 31,
                        "date": "2007-02-01 00:00:00",
                        "count": 124
                    }
                ]
            }
        }
